[package]
name = "r0_playground"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
playground-common = { path = "../../../common" }
risc0-zkvm = { version = "^2.0.1", default-features = false, features = ['std'] }
